name: sonaura_app
description: Sonaura - Free Music Streaming. No Ads. No Subscriptions. Ever.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7

  # Routing
  go_router: ^14.6.2

  # Networking
  dio: ^5.7.0
  connectivity_plus: ^6.1.0

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # UI Components
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  animations: ^2.0.11
  flutter_svg: ^2.0.14

  # Audio Player
  just_audio: ^0.9.40
  audio_service: ^0.18.15

  # File Management
  path_provider: ^2.1.5
  path: ^1.9.0
  crypto: ^3.0.6
  encrypt: ^5.0.3

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Platform Channels
  flutter_local_notifications: ^18.0.1

dev_desendencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^8.5.0
  mocktail: ^0.2.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
